name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20.x'

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      - name: Build and version info
        env:
          GIT_COMMIT: ${{ github.sha }}
          BUILD_DATE: ${{ github.run_id }}
        run: |
          go build -o rag-cli
          echo "Version: $(go list -m)" > version.txt
          echo "Git Commit: ${GIT_COMMIT}" >> version.txt
          echo "Build Date: $(date +"%Y-%m-%dT%H:%M:%SZ")" >> version.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            rag-cli
            version.txt
