name: Update Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'cmd/**'
      - 'internal/**'
      - 'pkg/**'
      - 'go.mod'
      - 'go.sum'

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Install dependencies
        run: go mod download

      - name: Build CLI
        run: go build -o rag-cli

      - name: Generate documentation
        run: ./rag-cli docs

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet docs/; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.changes.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git commit -m "Auto-update documentation [skip ci]"
          git push

      - name: Summary
        run: |
          if [[ "${{ steps.changes.outputs.changed }}" == "true" ]]; then
            echo "📚 Documentation updated successfully!"
          else
            echo "📖 Documentation is up to date."
          fi
